### ISSUE TITLE
无法连接数据库啊

### ISSUE THREAD

**Issue by 5sdba** [ww1516123/incubator-dolphinscheduler-app#1]
我把驱动复制到root@69e9ae3e74ac:/opt/dolphinscheduler/lib# 
重启容器也不行，添加连接源提示
![image](https://user-images.githubusercontent.com/19336613/81495502-3b661a00-92e3-11ea-8e7f-83a5ecccde54.png)

**Comment by ww1516123** [comment]
提供下错误日志。

**Comment by 5sdba** [comment]
自己搞定了，谢谢。

**Comment by yingliwuli** [comment]
docker-compose启动的，也出现了连接数据库失败

**Comment by yingliwuli** [comment]
是test，不是这个<scope>compile</scope>， 怎么加到容器呢
